using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Jeu421
{
    ///////////////////////////////////////////////////////////
    //  Alea.cs
    //  Implementation of the Class Alea
    //  Generated by Enterprise Architect
    //  Created on:      19-nov.-2009 14:38:47
    //  Original author: CHATELOT
    ///////////////////////////////////////////////////////////




    /// <summary>
    /// Dérive de la class Random
    /// </summary>
    public class Alea : Random
    {
        //Attribut
        private static Alea MonAlea = null;
        
        //Constructeur
        private Alea()
        {

        }


        //Méthodes
        public static Alea Instance()
        {

            if (MonAlea == null)
            {
                MonAlea = new Alea();

            }
            return MonAlea;	

        }

        /// 
        /// <param name="valMax"></param>
        /// <param name="valMin"></param>
        public int Nouveau(int valMin, int valMax)
        {

            return base.Next(valMin, valMax + 1);
        }

        /// 
        //<param name="valMax"></param>
        public int Nouveau(int valMax)
        {

            return base.Next(valMax + 1);

        }

        public double NouveauReel()
        {

            return base.NextDouble();

        }

    }//end Alea
}
