using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Jeu421
{
    ///////////////////////////////////////////////////////////
    //  De.cs
    //  Implementation of the Class De
    //  Generated by Enterprise Architect
    //  Created on:      19-nov.-2009 14:38:47
    //  Original author: CHATELOT
    ///////////////////////////////////////////////////////////




    public class De
    {
        //Atribut
        private int valeur;

        //Constructeur
        public De()
        {
            this.valeur = 0;        //initialisation
        }

        public void Jeter()
        {
          //  Alea hasard2 = new Alea();

            Alea hasard = Alea.Instance();
            this.valeur = hasard.Nouveau(1, 6);

        }

        /// <summary>
        /// Accesseur
        /// </summary>
        public int Valeur
        {
            get { return valeur; }
            set { valeur = value; }
        }

    }//end De
}
