using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Jeu421
{
    ///////////////////////////////////////////////////////////
    //  Lancer.cs
    //  Implementation of the Class Lancer
    //  Generated by Enterprise Architect
    //  Created on:      19-nov.-2009 14:38:47
    //  Original author: CHATELOT
    ///////////////////////////////////////////////////////////

    public class Lancer
    {
        //attribut
        private De [] les3Des=new De[3];

        //constructeur
        public Lancer()
        {
            for (int i = 0; i < 3; i++)
            {
                les3Des[i] = new De();
                les3Des[i].Jeter();
            }
            Trier();
           
          
            

        }
        
        //méthodes
        /// <summary>
        /// Vérifier si le lancer est gagnant
        /// </summary>
        public bool EstGagnant()
        {
            if (les3Des[0].Valeur == 4 && les3Des[1].Valeur == 2 && les3Des[2].Valeur == 1)
                return true;
            else
                return false;
        }

        /// <summary>
        /// Renvoie la valeur du Dé dont le numéro est entré en parametre
        /// </summary>
        /// <param name="numDe"></param>
        public int GetValeurDe(int numDe)
        {
            return les3Des[numDe].Valeur;
        }

        /// 
        /// <param name="numDe"></param>
        public void LancerUnDe(int numDe)
        {
            les3Des[numDe-1].Jeter();
            Trier();
            
        }

        /// <summary>
        /// Trier les des par orde décroissant
        /// </summary>
        private void Trier()                //Tri a bulle des dés
        {
            int tampon;
            bool continuer;
            do
            {
                continuer = false;
                for (int i = 0; i < 2; i++)
                {
                    if (les3Des[i].Valeur < les3Des[i+1].Valeur)
                    {
                        tampon = les3Des[i].Valeur;
                        les3Des[i].Valeur = les3Des[i+1].Valeur;
                        les3Des[i+1].Valeur=tampon;
                        
                        continuer = true;
                    }
                }
            }
            while (continuer);


        }


      
    }//end Lancer
}
