using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Jeu421
{
    ///////////////////////////////////////////////////////////
    //  Partie.cs
    //  Implementation of the Class Partie
    //  Generated by Enterprise Architect
    //  Created on:      19-nov.-2009 14:38:47
    //  Original author: CHATELOT
    ///////////////////////////////////////////////////////////
    public class Partie
    {
        //attributs
        private int nbMaxLancers;
        private int nbPoints;
        private int numLancer = 0;
        private Lancer manche;

        //Propriétés
        public int NbMaxLancers
        {
            get { return nbMaxLancers; }
        }
        public int NbPoints
        {
            get { return nbPoints; }
        }
        public int NumLancer
        {
            get { return numLancer; }
        }
        public Lancer Manche
        {
            get { return manche; }
        }

        //Constructeur
        public Partie(int n)
        {
           
          //manche = new Lancer();
            nbMaxLancers = n;
            nbPoints = 10 * n;
            
        }

        //Méthodes
        /// <summary>
        /// Dit si la partie est perdue ou pas
        /// </summary>
        public bool EstPerdue()
        {
            if (nbPoints <= 0)
                return true;
            else
                return false;
        }

        /// <summary>
        /// Met à jour le nombre de points du joueur
        /// </summary>
        public void MajPoints()
        {
            if (manche.EstGagnant())
                nbPoints += 30;
            else
                nbPoints -= 15;

        }

        /// <summary>
        /// Jette trois dés
        /// </summary>
        public void NouveauLancer()
        {
            numLancer++;
            manche = new Lancer();
        }

    }//end Partie
}
