using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Jeu421
{
    ///////////////////////////////////////////////////////////
    //  Test.cs
    //  Implementation of the Class Test
    //  Generated by Enterprise Architect
    //  Created on:      19-nov.-2009 14:38:47
    //  Original author: CHATELOT
    ///////////////////////////////////////////////////////////




    public class Test
    {
       
        /// 
        /// <param name="d"></param>
        public static void Affiche(De d)
        {
            Console.WriteLine(d.Valeur);

        }

        /// 
        /// <param name="l"></param>
        public static void Affiche(Lancer l)
        {
            for (int i = 0; i < 3; i++)
                Console.Write(l.GetValeurDe(i));
            Console.WriteLine();

        }
        public static int Verif(string s)
        {
            int choixDe = 0;
            bool valid = false;
            do
            {

                try
                {
                    choixDe = int.Parse(s);
                    valid = true;
                    if (choixDe < 1 || choixDe > 3)
                    {
                        Console.WriteLine("Ce n'est pas un numero de dé valide, entrer un autre numero (1,2,3)");
                        valid = false;
                    }
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);
                    Console.WriteLine("Ce n'est pas un numero de dé valide, entrer un autre numero (1,2,3)");
                    valid = false;
                }
                if (!valid) s = Console.ReadLine();
            }
            while (!valid);
            return choixDe;
        }
        public static void Recommencer(Partie pCourant, string strNbDes)
        {
            int nbrDes;
            int numDe;
            nbrDes = Verif(strNbDes);
            if (nbrDes == 3)
                for (numDe = 1; numDe<= 3; numDe++)
                    pCourant.Manche.LancerUnDe(numDe);
            else
            {
                for (int i = 1; i <= nbrDes; i++)
                {
                    if (nbrDes == 2)
                    {

                        if (i == 1)
                        {
                            Console.WriteLine("Quel est le " + i + "er dé que vous voulez rejouer (1,2,3)?");
                        }
                        else
                            Console.WriteLine("Quel est le " + i + "ème dé que vous voulez rejouer (1,2,3)?");
                    }
                    else
                    {
                        Console.WriteLine("Donner le numero du dé à rejouer");
                    }
                    numDe = Verif(Console.ReadLine());
                    pCourant.Manche.LancerUnDe(numDe);
                }
            }
        }

        public static void Run()
        {
            int reponse;
            /* De d = new De();
             Affiche(d);
             d.Jeter();
             Affiche(d);
             Console.Read();*/
            /*Lancer l = new Lancer();
            Affiche(l);
            l.LancerUnDe(2);
            Affiche(l);
            Console.Read();*/

           do
            { Console.WriteLine("Combien de manches voulez vous effectuer ?");
                reponse = int.Parse(Console.ReadLine());
            }
           while ( reponse<= 0);
                Partie p = new Partie(reponse);
                Console.WriteLine("Vous avez un capital de " + p.NbPoints + " points");
                int nbEssais;
                string strNbDes;
                do
                {
                    Console.WriteLine("Nouvelle manche");
                    p.NouveauLancer();
                    nbEssais = 1;
                    Console.WriteLine("Manche n°" + p.NumLancer + ", Essai n°1");
                    Affiche(p.Manche);
                    while (!p.Manche.EstGagnant() && nbEssais < 3)
                    {
                        Console.WriteLine("Combien de dés voulez-vous relancer (1,2,3)?");
                        strNbDes = Console.ReadLine();
                        Recommencer(p, strNbDes);
                        nbEssais++;
                        Console.WriteLine("Manche n°" + p.NumLancer + ", Essai n°" + nbEssais);
                        Affiche(p.Manche);

                    }
                    if (p.Manche.EstGagnant())
                        Console.WriteLine("Manche gagnée");
                    else
                        Console.WriteLine("Manche perdue");
                    p.MajPoints();
                    Console.WriteLine("Votre capital de points est passé à " + p.NbPoints + " points");
                    Console.WriteLine();
                    Console.ReadLine();
                }
                while (!(p.EstPerdue()) && p.NumLancer < p.NbMaxLancers);
                if (p.EstPerdue())
                    Console.WriteLine("Il ne vous reste plus de points : vous avez perdu la partie");
                else
                    Console.WriteLine("La partie est terminée : vous avez " + p.NbPoints + " points");

                Console.Read();

          

        }
    }//end Test
}
